version: '3.7'

services:
  spark-master:
    image: my-spark-image
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - "../:/opt/bitnami/spark/data"
    # network_mode: host
    ports:
      - "9090:8080"
      - "7077:7077"
  spark-worker-1:
    image: my-spark-image
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    image: my-spark-image
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077
